version: "3.8"

services:
  app:
    build: .
    container_name: DocuChat  # Changed container name to docuChat
    ports:
      - "8000:8000"  # Exposes FastAPI on port 8000
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}  # Assuming you're using an environment variable for the LLM API key
    volumes:
      - .:/app  # Mounts your project directory to the container for easy updates
    depends_on:
      - chroma  # Make sure ChromaDB is up before the FastAPI app starts

  chroma:
    image: ghcr.io/chroma-core/chroma:latest  # Example ChromaDB Docker image, replace if needed
    container_name: chromadb
    ports:
      - "6333:8000"  # Exposes ChromaDB on port 6333 (default)
    volumes:
      - chroma-data:/app/chroma_data  # Persist ChromaDB data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]  # Health check for ChromaDB
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  chroma-data: